### ISSUE TITLE
[Client] feature / sidebar 마이페이지 구현하기

### ISSUE THREAD

**Issue by Ma-SangHee** [codestates/Birth-Wiki-client#12]
### ISSUE

- Group: `client`
- Type:  `feature`
- Detail: 마이페이지 구현하기

### TODO

1. [x] 기본 HTML 작업
2. [x] 기본 CSS 작업
3. [x] 회원 닉네임 수정하기
4. [x]  회원 이미지 업로그 및 수정하기 

### Estimated time

> Pick one

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
