### ISSUE TITLE
[Client] Feature / 개발 환경 구축

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#13]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Development Settings

### TODO

1. [x] 개발 환경 구축(팀 공통)
    - linter
    - package.json 의존성 설정
    - .gitignore
    - .env
    - 개발 / 배포 환경 분리
2. [x] (임시) 더미 데이터 세팅 (카드 이미지 / 카테고리 목록)
3. [x] (임시) 컴포넌트 분류
4. [x] (임시) 기본 SPA 라우팅 적용

### Estimated time
-  `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `1w`
- Urgency: `High`
