### ISSUE TITLE
[Client] Feature / Favorite Page / 마크업 & 레이아웃 작성

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#15]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 레이아웃 작성

### TODO
1. [x] 필수 엘리먼트 리스트업
2. [x] 마크업 & 레이아웃 작성
3. [x] 기초 디자인 작업

### Estimated time
- `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `1w`
- Urgency: `High`
