### ISSUE TITLE
[Client] Stack / 타입스크립트 & Styled-components 학습 

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#16]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 타입스크립트 & Styled-components 학습

### TODO

1. [x] 타입스크립트 학습 환경 구성(설정)
2. [x] 기초 이론 학습
3. [x] Styled-components 적용해가며 실습

### Estimated time
- `3d`

### Labels
- Estimated time: `E: 3d`
- Group : `client`
- Sprint: `1w`
- Urgency: `High`
