### ISSUE TITLE
[Client] feature / CardClicked  카드 클릭시 나오는 기능 구현

### ISSUE THREAD

**Issue by stepperweb** [codestates/Birth-Wiki-client#21]
### ISSUE

- Group: `client`
- Type:  `feature`
- Detail: 카드목록 및 카드 내의 콘텐츠 추가

### TODO

1. [x] Birth Wiki 카드리스트 기능 구현 완성하기
2. [ ] Birth Wiki 카드리스트, 카드 Data 삽입
3. [ ] 전체적 기능 확인

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: 
- Urgency: `High`
