### ISSUE TITLE
[Client] feature / 메인페이지 나의 기록카드 기능 구현

### ISSUE THREAD

**Issue by stepperweb** [codestates/Birth-Wiki-client#22]
### ISSUE

- Group: `client`
- Type:  `feature`
- Detail: Birth Wiki 메인페이지 나의 기록카드 기능 구현하기

### TODO

1. [x] 나의 기록 카드 컴포넌트 작성
2. [ ] 유저 로그인 정보와 상호작용 나의 기록카드 목록 추가하기 기능 구현
3. [ ] 카드 기능 전체적으로 검사하기

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `
- Urgency: `High`
