### ISSUE TITLE
[Client] Feature / Favorite Page / Masonry 레이아웃 구현(PC)

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#29]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: Masonry 레이아웃 구현 (CSS Transform + 위치 계산 로직 활용)

### TODO
1. [x] ~~더미 이미지 10개로 테스트~~ Pixabay API 활용
2. [x] 이미지 세로 사이즈 엘리먼트에 반영되도록 구현(이미지 크기에 따라 요소의 세로 길이도 달라짐)
3. [x] 브라우저 사이즈 감소할 수록 컬럼(세로) 갯수도 감소

### Estimated time
- 2d

### Labels
- Estimated time: `E: 1d`
- Group : `client`
- Sprint: `2W`
- Urgency: `High`
