### ISSUE TITLE
[Client] Feature / Favorite Page / 상단 카테고리 목록 컴포넌트 작성

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#31]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 카테고리 목록 컴포넌트 작성

### TODO

1. [x] 카테고리 성격에 맞는 이미지 리서치
2. [x] 배경 이미지 어두운 블러처리 후 카테고리 텍스트 부곽
3. [x] 카테고리 버튼 클릭 시 해당 카테고리에 해당하는 카드만 보여지도록 필터링

### Estimated time
- `3h` 

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3W`
- Urgency: `High`
