### ISSUE TITLE
[Client] Feature / Favorite Page / 카드 마우스 오버 버튼 디자인

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#32]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: Masonry 레이아웃 각 카드에 대한 마우스 오버 버튼 디자인 작업

### TODO

1. [x] 즐겨찾기 해제(디자인)
2. [x] 즐겨찾기 해제(기능) 
2. [ ] ~~하단 카드에 해당하는 콘텐츠 소스 링크(디자인 + 기능)~~
3. [x] 공유 버튼(디자인)
4. [ ] ~~더 보기 기능(디자인)~~
5. [x] 카드 내용 자세히 보기 모달창

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3w`
- Urgency: `High`
