### ISSUE TITLE
[Client] Feature / Favorite Page / 더보기 버튼 기능 구현

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#35]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 카드의 더보기 버튼에 있는 각 기능 구현

### TODO

1. [ ] 현재 보고 있는 카드 이미지 형식으로 다운로드
2. [ ] 카드 숨기기 (#46 기능과 상태 공유)
3. [ ] 해당 카테고리의 다른 카드 보기

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `4w`
- Urgency: `Low`
