### ISSUE TITLE
[Client] Feature / Favorite Page / 카드 정렬 기능

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#36]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 카드 정렬 기능

### TODO

1. [ ] 최근 추가한 카드 순서로 정렬
2. [ ] 카드 사이즈 키우기 / 줄이기
3. [ ] 리스트 형태로 보기

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `4w`
- Urgency: `Low`
