### ISSUE TITLE
[Client] Feature / Favorite Page / 개별 카드 디자인(마우스 클릭 전)

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#37]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: Masonry 레이아웃에 포함하는 개별 카드의 세부 디자인

### TODO

1. [x] 메인 페이지에서 제작한 카드 디자인 톤앤매너에 맞춰 수정
2. [x] 우측 상단 카테고리 표시
3. [x] 사진 constrast 조정
2. [ ] ~(선택) 배경 전체 이미지 + 텍스트~
3. [ ] ~(선택) 상단 이미지 + 하단 텍스트~

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `2w`
- Urgency: `High`
