### ISSUE TITLE
[Client] Feature / Favorite Page / 개별 카드 디자인(마우스 클릭 후)

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#38]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 마우스 클릭 후 나오는 카드 상세내용에 대한 디자인 

### TODO

1. [x] 메인 페이지에서 제작한 카드 디자인 톤앤매너에 맞춰 수정
2. [x] (선택) 좌 이미지 + 우 텍스트
3. [ ] (선택) 상 이미지 + 하 텍스트
4. [ ] (선택) 배경 전체 이미지 + 텍스트

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3w`
- Urgency: `High`
