### ISSUE TITLE
[Client] Feature / Favorite Page / 개별 카드 기능 버튼 추가(마우스 클릭 후)

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#39]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 마우스 클릭 후 나오는 카드 상세 내용에 기능 버튼 추가

### TODO
버튼 디자인은 #32 그대로 활용

1. [ ] ~출처 버튼~
2. [x] 하트 버튼 (클릭 시 즐겨찾기 해제)
3. [x] 공유 버튼(기능 구현은 #34 Advanced)
4. [ ] ~더보기 버튼(기능 구현은 #35 Advanced)~

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3w`
- Urgency: `High`
