### ISSUE TITLE
[Client] Feature / Favorite Page / 모바일 화면 하단 플로팅 메뉴 구현

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#42]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 모바일 화면 플로팅 메뉴 구현

### TODO

1. [ ] 홈으로 이동 버튼
2. [ ] 검색 버튼(기능 구현 별개 #45 Advanced)
3. [ ] 숨긴 카드 보기(기능 구현 별개 #46 Advanced)
4. [ ] 프로필 이미지 버튼(Mypage로 이동)

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3w`
- Urgency: `High`
