### ISSUE TITLE
[Client] Feature / Favorite Page / 카드 상세보기 모달창 모바일 사이즈 대응

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#68]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 카드 상세보기 모달창 모바일 화면 대응(반응형)

### TODO

1. [x] 이미지 / 텍스트 영역 배치 조정(Grid 활용)
2. [x] 기능 버튼(아이콘) 색상 변경
3. [x] 모달창 최대 사이즈 지정
4. [x] 스크롤바 디자인 조정

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3W`
- Urgency: `High`
