### ISSUE TITLE
[Client] Feature / Favorite Page / 메인 컴포넌트 데이터 연결 및 코드 수정 작업

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#73]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 메인 페이지 상태 데이터 연결 및 관련 코드 수정 작업

### TODO

1. [x] 기존 더미 데이터 -> 메인 페이지 상태 데이터로 교체
2. [x] 무한 스크롤 로직 수정(한 페이지당 콘텐츠 얼마나 노출할지, totalPage 로직은 어떻게 변경할지 등)
3. [x] 무한 스크롤 로딩 로직 수정
3. [x] 기존 useEffect 코드 정리(fetchImage 함수 -> useSelector 데이터로 변경)
4. [x] 가로 이미지 처리(리사이즈 함수 생성)

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3w`
- Urgency: `High`
