### ISSUE TITLE
[Client] Feature / Favorite Page / 영화 및 음악 카테고리 추가 작업

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#82]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 영화 및 음악 카테고리 추가 작업

### TODO

1. [x] 일반 카테고리 및 미디어 카테고리 속성 타입 정리 작업
2. [x] 렌더 로직 수정
3. [x] 카드 디자인 및 로직 수정
4. [x] 모달창 디자인 및 로직 수정

### Estimated time
- `3h`

### Labels

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `4W`
- Urgency: `High`
