### ISSUE TITLE
[Client] Feature / Favorite Page / 마지막 개선 리스트

### ISSUE THREAD

**Issue by romantech** [codestates/Birth-Wiki-client#91]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 프로젝트 종료 전 개선해야할 목록들

### TODO

1. [x] 각 카드에 연도 혹은 날짜 추가
2. [x] 플립 카드내 공유 버튼 -> 확대 버튼으로 교체
2. [x] 스크롤 끝에 도달했을 때 나오는 메시지 수정
3. [x] 영화 / 음악 카드 상세보기내 커버 이미지 추가
3. [ ] 좋아요 취소 누를 때 애니메이션(렌더 애니메이션 알아보기)
4. [x] contents 배열 길이에 따라 이미지 사이즈 다르게
5. [x] 영화, 음악 포스트 이미지 있을 시 해당 이미지로 렌더
6. [x] 로딩전/로딩중 이미지 영역 회색으로 나오게 조정
7. [ ] MyCards 카테고리 추가
8. [x] 영화 평점 데이터 추가
9. [x] 영화 평점 별 개수 로직 추가
10. [x] 프로필 카드 이미지 원형으로 변경
11. [x] 서버에서 받아온 이미지 주소가 403 에러일 때 조건 처리

### Estimated time
- `3d`

### Labels

- Estimated time: `E: 3d`
- Group : `client`
- Sprint: `4W`
- Urgency: `Middle`
